service:
  name: notification

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  send_email:
    handler: email-notification/handler.sendEmail
    role: ${ssm:${self:custom.stage}-email-iam-role}
    events:
      - sqs: ${ssm:${self:custom.stage}-email-sqs}
    environment:
      SMTP_SERVER: ${ssm:${self:custom.stage}-smtp-server}
      EMAIL_FROM: ${ssm:${self:custom.stage}-email-from}
      EMAIL_TO: ${ssm:${self:custom.stage}-email-to}
      EMAIL_FROM_PASSWORD: ${ssm:${self:custom.stage}-email-from-password}

  send_sms:
    handler: sms-notification/handler.sendSms
    role: ${ssm:${self:custom.stage}-sms-iam-role}
    events:
      - sqs: ${ssm:${self:custom.stage}-sms-sqs}
    environment:
      MESSAGE_BIRD_API_KEY: ${ssm:${self:custom.stage}-message-bird-api-key}
      SMS_PHONE_FROM: ${ssm:${self:custom.stage}-sms-phone-from}
      SMS_PHONE_TO: ${ssm:${self:custom.stage}-sms-phone-to}

custom:
  stage: ${opt:stage, self:provider.stage}
